"""add portfolio goals table

Revision ID: b3ceb67dbcd7
Revises: c1ca906ef846
Create Date: 2026-04-15 20:30:39.773609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ceb67dbcd7'
down_revision: Union[str, None] = 'c1ca906ef846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension', 'name', name='uq_goal_dimension_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_goals')
    # ### end Alembic commands ###
