"""add dividends table

Revision ID: c1ca906ef846
Revises: d4e5f6a7b890
Create Date: 2026-04-14 18:10:13.886846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ca906ef846'
down_revision: Union[str, None] = 'd4e5f6a7b890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('dividend_date', sa.Date(), nullable=False),
    sa.Column('local_currency', sa.String(length=3), nullable=False),
    sa.Column('local_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('gross_amount_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('withholding_tax_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin', 'dividend_date', name='uq_dividend_isin_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dividends')
    # ### end Alembic commands ###
