"""add local_currency to transactions

Revision ID: f755440c3bac
Revises: 51a8fc21edd0
Create Date: 2026-04-06 19:05:56.051035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f755440c3bac'
down_revision: Union[str, None] = '51a8fc21edd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('local_currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'local_currency')
    # ### end Alembic commands ###
